/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package LoginandRegister;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.*;
import java.util.*;
import java.sql.DriverManager;
import net.proteanit.sql.DbUtils;
import java.text.SimpleDateFormat;  
import java.util.Date;  


public class Registration extends javax.swing.JFrame {

    /** Creates new form Registration */
    public Registration() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CanceButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        firstname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        retypePassword = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        RollNo = new javax.swing.JTextField();
        CanceButton1 = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        db = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        CanceButton.setBackground(new java.awt.Color(102, 0, 102));
        CanceButton.setForeground(new java.awt.Color(102, 0, 102));
        CanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanceButtonActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.setToolTipText("");
        jPanel3.setLayout(null);

        firstname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        jPanel3.add(firstname);
        firstname.setBounds(160, 100, 220, 30);

        jLabel1.setBackground(new java.awt.Color(153, 0, 153));
        jLabel1.setFont(new java.awt.Font("Bodoni MT Condensed", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registeration");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(60, 10, 320, 70);

        loginButton.setBackground(new java.awt.Color(255, 255, 255));
        loginButton.setForeground(new java.awt.Color(102, 0, 102));
        loginButton.setText("LOGIN");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel3.add(loginButton);
        loginButton.setBounds(270, 450, 120, 40);

        jLabel6.setFont(new java.awt.Font("HP Simplified Hans", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Roll No");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(50, 300, 100, 40);

        jLabel7.setFont(new java.awt.Font("HP Simplified Hans", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Retype Password");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(50, 380, 100, 40);

        gender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male ", "Other" }));
        jPanel3.add(gender);
        gender.setBounds(160, 220, 120, 30);

        jLabel10.setFont(new java.awt.Font("HP Simplified Hans", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Gender");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(50, 220, 90, 40);

        jLabel11.setFont(new java.awt.Font("HP Simplified Hans", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Password");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(60, 340, 90, 40);

        password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(password);
        password.setBounds(160, 340, 220, 30);

        retypePassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(retypePassword);
        retypePassword.setBounds(160, 380, 220, 30);

        jLabel8.setFont(new java.awt.Font("HP Simplified Hans", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Address");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(50, 180, 100, 40);

        RollNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RollNoActionPerformed(evt);
            }
        });
        jPanel3.add(RollNo);
        RollNo.setBounds(160, 300, 220, 30);

        CanceButton1.setBackground(new java.awt.Color(255, 255, 255));
        CanceButton1.setForeground(new java.awt.Color(102, 0, 102));
        CanceButton1.setText("CANCEL");
        CanceButton1.setActionCommand("");
        CanceButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanceButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(CanceButton1);
        CanceButton1.setBounds(100, 450, 120, 40);

        email.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel3.add(email);
        email.setBounds(160, 260, 220, 30);

        jLabel9.setFont(new java.awt.Font("HP Simplified Hans", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Email id");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(50, 260, 100, 40);
        jPanel3.add(db);
        db.setBounds(160, 140, 220, 30);

        jLabel12.setFont(new java.awt.Font("HP Simplified Hans", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Name");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(50, 100, 100, 40);

        address.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        jPanel3.add(address);
        address.setBounds(160, 180, 220, 30);

        jLabel13.setFont(new java.awt.Font("HP Simplified Hans", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Date of birth");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(50, 140, 100, 40);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

        String fname,rollNo,gndr,psswd,retypePsswd,el,addrs;
        fname = firstname.getText();
        rollNo= RollNo.getText();
        gndr=gender.getSelectedItem().toString();
        el = email.getText().toString();
        addrs = address.getText().toString();
        SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
        String dob = dFormat.format(db.getDate());
        psswd = new String(password.getPassword());
        retypePsswd = new String(retypePassword.getPassword());
        
        
            if(("".equals(fname))|| ("".equals(rollNo))  ||("".equals(gndr)) || ("".equals(psswd)) || ("".equals(el)) || ("".equals(addrs)) || ("".equals(db)))
            {
                System.out.println();
                JOptionPane.showMessageDialog(null, "Please enter all the fields");

            }
        
            else
            {
                if(!el.contains("@")){
                    JOptionPane.showMessageDialog(null, "Please enter correct email id");
                }else{
                    if(!psswd.equals(retypePsswd)){
                        System.out.println();
                        JOptionPane.showMessageDialog(null, "Password not matched");
                    }
                    
                    
                    else{
                        PreparedStatement ps;
                        String query = "INSERT INTO `student`(`FullName`, `RollNo`, `Gender`, `password` , `Email` ,`Address`,`DOB`) VALUES (?,?,?,?,?,?,?)";

                        try{
                            ps = myConnection.getConnection().prepareStatement(query);
                            ps.setString(1,fname);
                            ps.setString(2,rollNo);
                            ps.setString(3,gndr);
                            ps.setString(4,psswd);
                            ps.setString(5,el);
                            ps.setString(6,addrs);
                            
                            java.util.Date javaDate = dFormat.parse(dob);
                            java.sql.Date sqlDate = new java.sql.Date(javaDate.getTime());
                            
                            ps.setDate(7,sqlDate);
                            if(ps.executeUpdate()>0){
                                System.out.println();
                                JOptionPane.showMessageDialog(null, "New Student Added");
                            }

                            Student s=new Student();
                            s.setVisible(true);
                            this.dispose();
                        }catch(Exception e){
                            System.out.println(e.getMessage());
                        }
                    }
                }
            }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void CanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanceButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CanceButtonActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void RollNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RollNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RollNoActionPerformed

    private void CanceButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanceButton1ActionPerformed
       int resp = JOptionPane.showConfirmDialog(null, 
                "Are you sure to clear all entered details?","CANCEL", JOptionPane.YES_NO_OPTION);
           if (resp == JOptionPane.YES_OPTION) {
        firstname.setText("");
        RollNo.setText("");
        address.setText("");
        email.setText("");
        db.setDate(null);
        password.setText("");
        retypePassword.setText("");
           }
    }//GEN-LAST:event_CanceButton1ActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CanceButton;
    private javax.swing.JButton CanceButton1;
    private javax.swing.JTextField RollNo;
    private javax.swing.JTextField address;
    private com.toedter.calendar.JDateChooser db;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstname;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField retypePassword;
    // End of variables declaration//GEN-END:variables

}
